version: '2'

services:
  keto-migrate:
    image: oryd/keto
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  keto:
    image: oryd/keto
    links:
      - postgresd:postgresd
    ports:
      - "4466:4466"
    depends_on:
      - keto-migrate
    command:
      serve
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  postgresd:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb
    volumes:
      - database:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bundle exec rspec
    depends_on:
      - keto
    volumes:
      - ./:/usr/local/src
    environment:
      - KETO_ENDPOINT=http://keto:4466

volumes:
  database:
